name: Build lzCEFD Win64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Win64 single EXE
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lzCEFD-win64
        path: bin/Release/net6.0-windows/win-x64/publish/
